[package]
name = "lang"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
peg = { version = "0.8.4" }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[features]
default = []
trace = ["peg/trace"]
